-- GENERATED FILE. Run tools/generate_lua_dataset.py to regenerate.
-- Source: database/entries/*-dataset.json. Do not hand-edit.

local LoreBuddyCore = _G.LoreBuddyCore or {}
_G.LoreBuddyCore = LoreBuddyCore

LoreBuddyCore.GeneratedDataset = {
  ["entities"] = {
    {
      ["id"] = "sample_illidan_stormrage",
      ["name"] = "[Sample] Illidan Stormrage",
      ["type"] = "character",
      ["aliases"] = {
        "[Sample] The Betrayer",
      },
      ["summary"] = "Placeholder summary sentence for architecture testing.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "draft",
      ["eraId"] = "era_burning_crusade",
      ["loreRelevance"] = "core",
      ["priority"] = "p0",
      ["chronology"] = {
        ["absolute"] = "unknown",
        ["relative"] = "Imprisoned during the War of the Ancients; released during the Third War.",
        ["beforeEventIds"] = {
          "sample_war_of_the_ancients",
        },
        ["afterEventIds"] = {
          "sample_fall_of_the_black_temple",
        },
        ["notes"] = "Placeholder chronology notes.",
      },
    },
    {
      ["id"] = "sample_malfurion_stormrage",
      ["name"] = "[Sample] Malfurion Stormrage",
      ["type"] = "character",
      ["summary"] = "Placeholder summary sentence for architecture testing.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "draft",
      ["eraId"] = "era_war_of_the_ancients",
      ["loreRelevance"] = "important",
      ["priority"] = "p1",
    },
    {
      ["id"] = "sample_the_illidari",
      ["name"] = "[Sample] The Illidari",
      ["type"] = "organization",
      ["summary"] = "Placeholder faction summary for architecture testing.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "draft",
      ["eraId"] = "era_burning_crusade",
      ["loreRelevance"] = "important",
      ["priority"] = "p1",
    },
    {
      ["id"] = "sample_black_temple",
      ["name"] = "[Sample] Black Temple",
      ["type"] = "raid",
      ["summary"] = "Placeholder location summary for architecture testing.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "draft",
      ["eraId"] = "era_burning_crusade",
      ["loreRelevance"] = "core",
      ["priority"] = "p1",
    },
    {
      ["id"] = "sample_war_of_the_ancients",
      ["name"] = "[Sample] War of the Ancients",
      ["type"] = "event",
      ["summary"] = "Placeholder event summary for architecture testing.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "draft",
      ["eraId"] = "era_war_of_the_ancients",
      ["loreRelevance"] = "important",
      ["priority"] = "p2",
      ["chronology"] = {
        ["absolute"] = "unknown",
        ["relative"] = "Long before the First War.",
        ["notes"] = "Placeholder; exact date intentionally left unknown, per policy of never fabricating dates.",
      },
    },
    {
      ["id"] = "sample_fall_of_the_black_temple",
      ["name"] = "[Sample] Fall of the Black Temple",
      ["type"] = "event",
      ["summary"] = "Placeholder event summary for architecture testing.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "draft",
      ["eraId"] = "era_burning_crusade",
      ["loreRelevance"] = "core",
      ["priority"] = "p1",
      ["chronology"] = {
        ["absolute"] = "unknown",
        ["relative"] = "During the Burning Crusade.",
        ["beforeEventIds"] = {},
        ["afterEventIds"] = {},
      },
    },
    {
      ["id"] = "example_wayfinder",
      ["name"] = "Example Wayfinder",
      ["type"] = "character",
      ["aliases"] = {
        "The Wayfinder",
      },
      ["summary"] = "A fictional character used to prove the LoreBuddy data model.",
      ["gameVersions"] = {
        "fixture",
      },
      ["status"] = "draft",
    },
    {
      ["id"] = "example_waypoint",
      ["name"] = "Example Waypoint",
      ["type"] = "location",
      ["summary"] = "A fictional location used to prove the LoreBuddy data model.",
      ["gameVersions"] = {
        "fixture",
      },
      ["status"] = "draft",
    },
    {
      ["id"] = "illidan_stormrage",
      ["name"] = "Illidan Stormrage",
      ["type"] = "character",
      ["aliases"] = {
        "The Betrayer",
        "Lord of Outland",
      },
      ["summary"] = "Twin brother of Malfurion, an outcast night elf who became the first demon hunter and ruled Outland from the Black Temple.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "malfurion_stormrage",
      ["name"] = "Malfurion Stormrage",
      ["type"] = "character",
      ["aliases"] = {
        "Archdruid",
      },
      ["summary"] = "Illidan's twin brother, the first druid of the night elves and consort of Tyrande Whisperwind.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "tyrande_whisperwind",
      ["name"] = "Tyrande Whisperwind",
      ["type"] = "character",
      ["summary"] = "High Priestess of Elune and leader of the night elves, bound by history to both Stormrage brothers.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "maiev_shadowsong",
      ["name"] = "Maiev Shadowsong",
      ["type"] = "character",
      ["summary"] = "Warden of the night elves who imprisoned Illidan for ten thousand years and pursued him across two continents.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "akama",
      ["name"] = "Akama",
      ["type"] = "character",
      ["summary"] = "A broken draenei leader who served Illidan in Outland before secretly working to end his rule.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "kaelthas_sunstrider",
      ["name"] = "Kael'thas Sunstrider",
      ["type"] = "character",
      ["aliases"] = {
        "Kael'thas",
        "Prince Kael'thas",
      },
      ["summary"] = "Prince of the blood elves who pledged his people to Illidan in exchange for a cure to their magic addiction.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "lady_vashj",
      ["name"] = "Lady Vashj",
      ["type"] = "character",
      ["summary"] = "A naga sorceress and one of Illidan's most trusted lieutenants, commanding his forces in Outland's waters.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "guldan",
      ["name"] = "Gul'dan",
      ["type"] = "character",
      ["summary"] = "An orc warlock whose skull became a source of demonic power long after his death.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "black_temple",
      ["name"] = "Black Temple",
      ["type"] = "raid",
      ["aliases"] = {
        "Temple of Karabor",
      },
      ["summary"] = "A draenei temple in Shadowmoon Valley that Illidan seized and made his stronghold in Outland.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "outland",
      ["name"] = "Outland",
      ["type"] = "zone",
      ["summary"] = "The shattered remains of the orc homeworld Draenor, and the setting for Illidan's exile and rule.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "skull_of_guldan",
      ["name"] = "Skull of Gul'dan",
      ["type"] = "item",
      ["summary"] = "A demonic artifact whose fel energy transformed Illidan into a demon during the Third War.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "the_illidari",
      ["name"] = "The Illidari",
      ["type"] = "organization",
      ["aliases"] = {
        "Demon Hunters",
      },
      ["summary"] = "The order of demon hunters trained by Illidan to fight the Burning Legion with its own methods.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "war_of_the_ancients",
      ["name"] = "War of the Ancients",
      ["type"] = "event",
      ["summary"] = "An ancient war against the Burning Legion during which Illidan first clashed with his brother over the Well of Eternity.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "fall_of_the_black_temple",
      ["name"] = "Fall of the Black Temple",
      ["type"] = "event",
      ["aliases"] = {
        "Battle for the Black Temple",
      },
      ["summary"] = "The battle in which adventurers, Akama, and Maiev Shadowsong ended Illidan's rule over Outland.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "hellfire_peninsula",
      ["name"] = "Hellfire Peninsula",
      ["type"] = "zone",
      ["summary"] = "The scarred region surrounding the Dark Portal, and the first zone most adventurers reach when entering Outland.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "arthas_menethil",
      ["name"] = "Arthas Menethil",
      ["type"] = "character",
      ["aliases"] = {
        "The Lich King",
      },
      ["summary"] = "Crown Prince of Lordaeron whose fall to corruption during the Third War led to the destruction of his own kingdom.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "active",
      ["eraId"] = "era_third_war",
      ["loreRelevance"] = "core",
      ["priority"] = "p0",
      ["chronology"] = {
        ["absolute"] = "unknown",
        ["relative"] = "During and after the Third War.",
        ["afterEventIds"] = {
          "third_war",
        },
        ["notes"] = "Placeholder-free summary; exact in-universe dates intentionally omitted.",
      },
    },
    {
      ["id"] = "jaina_proudmoore",
      ["name"] = "Jaina Proudmoore",
      ["type"] = "character",
      ["summary"] = "A human sorceress and one of Arthas's closest companions before the Third War's devastation.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "active",
      ["eraId"] = "era_third_war",
      ["loreRelevance"] = "important",
      ["priority"] = "p1",
    },
    {
      ["id"] = "uther",
      ["name"] = "Uther",
      ["type"] = "character",
      ["aliases"] = {
        "Uther the Lightbringer",
      },
      ["summary"] = "A paladin of the Silver Hand and Arthas's mentor, ultimately struck down by his own student.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "retired",
      ["eraId"] = "era_third_war",
      ["loreRelevance"] = "important",
      ["priority"] = "p1",
    },
    {
      ["id"] = "kelthuzad",
      ["name"] = "Kel'Thuzad",
      ["type"] = "character",
      ["summary"] = "A human archmage who abandoned the Kirin Tor to found the Cult of the Damned in service to the Lich King.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "active",
      ["eraId"] = "era_third_war",
      ["loreRelevance"] = "important",
      ["priority"] = "p1",
    },
    {
      ["id"] = "sylvanas_windrunner",
      ["name"] = "Sylvanas Windrunner",
      ["type"] = "character",
      ["aliases"] = {
        "The Banshee Queen",
      },
      ["summary"] = "Former Ranger-General of Silvermoon, slain and raised by the Scourge before breaking free to found the Forsaken.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "active",
      ["eraId"] = "era_third_war",
      ["loreRelevance"] = "important",
      ["priority"] = "p1",
    },
    {
      ["id"] = "the_scourge",
      ["name"] = "The Scourge",
      ["type"] = "faction",
      ["summary"] = "The undead army raised by the Lich King to sweep across Lordaeron during the Third War.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "active",
      ["eraId"] = "era_third_war",
      ["loreRelevance"] = "core",
      ["priority"] = "p1",
    },
    {
      ["id"] = "the_forsaken",
      ["name"] = "The Forsaken",
      ["type"] = "faction",
      ["summary"] = "Undead who broke free of the Lich King's control under Sylvanas Windrunner's leadership.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "active",
      ["eraId"] = "era_third_war",
      ["loreRelevance"] = "important",
      ["priority"] = "p1",
    },
    {
      ["id"] = "lordaeron",
      ["name"] = "Lordaeron",
      ["type"] = "zone",
      ["summary"] = "The human kingdom whose capital fell during the Scourge invasion of the Third War.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "retired",
      ["eraId"] = "era_third_war",
      ["loreRelevance"] = "important",
      ["priority"] = "p1",
    },
    {
      ["id"] = "third_war",
      ["name"] = "Third War",
      ["type"] = "event",
      ["summary"] = "The Scourge invasion of Lordaeron and the wider conflict that reshaped Azeroth's factions.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "active",
      ["eraId"] = "era_third_war",
      ["loreRelevance"] = "core",
      ["priority"] = "p1",
      ["chronology"] = {
        ["absolute"] = "unknown",
        ["relative"] = "After the Second War, before Classic-era Azeroth.",
        ["notes"] = "Placeholder-free; exact date intentionally omitted.",
      },
    },
    {
      ["id"] = "fall_of_lordaeron",
      ["name"] = "Fall of Lordaeron",
      ["type"] = "event",
      ["summary"] = "The destruction of the kingdom of Lordaeron at Arthas's hand, marking the height of the Scourge invasion.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "active",
      ["eraId"] = "era_fall_of_lordaeron",
      ["loreRelevance"] = "core",
      ["priority"] = "p1",
    },
    {
      ["id"] = "dark_portal",
      ["name"] = "Dark Portal",
      ["type"] = "location",
      ["aliases"] = {
        "The Dark Portal",
      },
      ["summary"] = "A magical portal linking Azeroth to Draenor and, after its destruction and reopening, to Outland.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "medivh",
      ["name"] = "Medivh",
      ["type"] = "character",
      ["aliases"] = {
        "The Last Guardian",
      },
      ["summary"] = "The last Guardian of Tirisfal, whose corrupted actions opened the original Dark Portal.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "khadgar",
      ["name"] = "Khadgar",
      ["type"] = "character",
      ["aliases"] = {
        "Archmage Khadgar",
      },
      ["summary"] = "A young mage who served as Medivh's apprentice and later became a key Alliance leader guiding adventurers into Outland.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "draenor",
      ["name"] = "Draenor",
      ["type"] = "zone",
      ["summary"] = "The orc homeworld beyond the Dark Portal, later shattered into Outland.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "retired",
    },
    {
      ["id"] = "the_horde",
      ["name"] = "The Horde",
      ["type"] = "faction",
      ["aliases"] = {
        "Horde",
      },
      ["summary"] = "A coalition originally formed by the orc clans after arriving on Azeroth, later reorganized by Thrall.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "the_alliance",
      ["name"] = "The Alliance",
      ["type"] = "faction",
      ["aliases"] = {
        "Alliance",
      },
      ["summary"] = "A coalition of humans, dwarves, night elves, gnomes, and other races formed to oppose the orcish invasions.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "thrall",
      ["name"] = "Thrall",
      ["type"] = "character",
      ["aliases"] = {
        "Go'el",
      },
      ["summary"] = "Warchief who freed the orcs from internment camps and reformed the Horde on Kalimdor.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "cho_gall",
      ["name"] = "Cho'gall",
      ["type"] = "character",
      ["summary"] = "A leader of the Twilight's Hammer cult who reopened the Dark Portal shortly before the Burning Crusade.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "first_war",
      ["name"] = "First War",
      ["type"] = "event",
      ["summary"] = "The initial orcish invasion of Azeroth through the Dark Portal, beginning centuries of conflict between orcs and humans.",
      ["gameVersions"] = {
        "classic",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "blasted_lands",
      ["name"] = "Blasted Lands",
      ["type"] = "zone",
      ["summary"] = "A scarred region of Azeroth surrounding the Dark Portal, transformed by the portal's destruction and reopening.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "nethergarde_keep",
      ["name"] = "Nethergarde Keep",
      ["type"] = "location",
      ["summary"] = "An Alliance fortress in the Blasted Lands built to watch over the Dark Portal.",
      ["gameVersions"] = {
        "classic",
        "tbc",
      },
      ["status"] = "active",
    },
    {
      ["id"] = "opening_of_the_dark_portal",
      ["name"] = "Opening of the Dark Portal",
      ["type"] = "event",
      ["aliases"] = {
        "Reopening of the Dark Portal",
      },
      ["summary"] = "The world event in which Cho'gall reopened the Dark Portal, allowing adventurers to journey into Outland.",
      ["gameVersions"] = {
        "tbc",
      },
      ["status"] = "active",
    },
  },
  ["sources"] = {
    {
      ["id"] = "sample_src_placeholder_primary",
      ["publisher"] = "[Sample] Blizzard Entertainment",
      ["title"] = "[Sample] Placeholder primary source",
      ["kind"] = "blizzard_api",
      ["classification"] = "primary",
      ["reference"] = "placeholder-reference-only",
      ["attribution"] = "[Sample] Blizzard Entertainment",
      ["license"] = "Placeholder; do not reuse",
      ["verificationStatus"] = "unverified",
      ["confidence"] = "confirmed",
    },
    {
      ["id"] = "sample_src_placeholder_secondary",
      ["publisher"] = "[Sample] Community Wiki",
      ["title"] = "[Sample] Placeholder secondary source",
      ["kind"] = "external_reference",
      ["classification"] = "secondary",
      ["reference"] = "placeholder-reference-only",
      ["attribution"] = "[Sample] Community Wiki contributors",
      ["license"] = "Placeholder; do not reuse",
      ["verificationStatus"] = "unverified",
      ["confidence"] = "strongly_supported",
    },
    {
      ["id"] = "sample_src_conflicting_retcon",
      ["publisher"] = "[Sample] Older Sourcebook",
      ["title"] = "[Sample] Placeholder source demonstrating a documented retcon",
      ["kind"] = "book",
      ["classification"] = "secondary",
      ["reference"] = "placeholder-reference-only",
      ["attribution"] = "[Sample] Older Sourcebook authors",
      ["license"] = "Placeholder; do not reuse",
      ["verificationStatus"] = "reviewed",
      ["confidence"] = "conflicting",
      ["retconNotes"] = "Placeholder: this source's account was later superseded by a newer, more authoritative source. Both are kept on file rather than silently overwritten; see the statement's canonStatus and epistemicStatus.",
    },
    {
      ["id"] = "fixture_author_note",
      ["publisher"] = "LoreBuddy Contributors",
      ["title"] = "Example fixture author note",
      ["kind"] = "community_contribution",
      ["classification"] = "community",
      ["reference"] = "database/entries/example-dataset.json",
      ["attribution"] = "LoreBuddy fixture contributors",
      ["license"] = "MIT; fictional test content",
      ["verificationStatus"] = "verified",
    },
    {
      ["id"] = "src_lorebuddy_contributors",
      ["publisher"] = "LoreBuddy Contributors",
      ["title"] = "LoreBuddy original lore summaries",
      ["kind"] = "community_contribution",
      ["classification"] = "community",
      ["reference"] = "database/entries/illidan-vertical-slice-dataset.json",
      ["attribution"] = "LoreBuddy Contributors",
      ["license"] = "MIT; original summaries written for LoreBuddy",
      ["verificationStatus"] = "reviewed",
    },
    {
      ["id"] = "src_warcraft_wiki_illidan",
      ["publisher"] = "Warcraft Wiki (wiki.gg)",
      ["title"] = "Illidan Stormrage — Warcraft Wiki",
      ["kind"] = "external_reference",
      ["classification"] = "secondary",
      ["reference"] = "https://warcraft.wiki.gg/wiki/Illidan_Stormrage",
      ["url"] = "https://warcraft.wiki.gg/wiki/Illidan_Stormrage",
      ["attribution"] = "Warcraft Wiki contributors",
      ["license"] = "CC BY-SA 4.0",
      ["verificationStatus"] = "unverified",
    },
    {
      ["id"] = "src_wowhead_black_temple",
      ["publisher"] = "Wowhead",
      ["title"] = "Black Temple — Wowhead search",
      ["kind"] = "external_reference",
      ["classification"] = "secondary",
      ["reference"] = "https://www.wowhead.com/search?q=Black+Temple",
      ["url"] = "https://www.wowhead.com/search?q=Black+Temple",
      ["attribution"] = "Wowhead",
      ["license"] = "Proprietary; reference link only, do not copy text",
      ["verificationStatus"] = "unverified",
    },
    {
      ["id"] = "src_lorebuddy_third_war_contributors",
      ["publisher"] = "LoreBuddy Contributors",
      ["title"] = "LoreBuddy original lore summaries (Third War / Fall of Lordaeron)",
      ["kind"] = "community_contribution",
      ["classification"] = "community",
      ["reference"] = "database/entries/third-war-fall-of-lordaeron-dataset.json",
      ["attribution"] = "LoreBuddy Contributors",
      ["license"] = "MIT; original summaries written for LoreBuddy",
      ["verificationStatus"] = "reviewed",
      ["confidence"] = "strongly_supported",
    },
    {
      ["id"] = "src_warcraft_wiki_third_war",
      ["publisher"] = "Warcraft Wiki (wiki.gg)",
      ["title"] = "Third War — Warcraft Wiki search",
      ["kind"] = "external_reference",
      ["classification"] = "secondary",
      ["reference"] = "https://warcraft.wiki.gg/index.php?search=Third+War",
      ["url"] = "https://warcraft.wiki.gg/index.php?search=Third+War",
      ["attribution"] = "Warcraft Wiki contributors",
      ["license"] = "CC BY-SA 4.0",
      ["verificationStatus"] = "unverified",
      ["confidence"] = "strongly_supported",
    },
    {
      ["id"] = "src_wowhead_third_war",
      ["publisher"] = "Wowhead",
      ["title"] = "Arthas Menethil — Wowhead search",
      ["kind"] = "external_reference",
      ["classification"] = "secondary",
      ["reference"] = "https://www.wowhead.com/search?q=Arthas+Menethil",
      ["url"] = "https://www.wowhead.com/search?q=Arthas+Menethil",
      ["attribution"] = "Wowhead",
      ["license"] = "Proprietary; reference link only, do not copy text",
      ["verificationStatus"] = "unverified",
      ["confidence"] = "strongly_supported",
    },
    {
      ["id"] = "src_lorebuddy_tier1_contributors",
      ["publisher"] = "LoreBuddy Contributors",
      ["title"] = "LoreBuddy original lore summaries (Tier 1: Azeroth prerequisite lore)",
      ["kind"] = "community_contribution",
      ["classification"] = "community",
      ["reference"] = "database/entries/tier1-azeroth-prerequisite-dataset.json",
      ["attribution"] = "LoreBuddy Contributors",
      ["license"] = "MIT; original summaries written for LoreBuddy",
      ["verificationStatus"] = "reviewed",
    },
    {
      ["id"] = "src_warcraft_wiki_classic_lore",
      ["publisher"] = "Warcraft Wiki (wiki.gg)",
      ["title"] = "Dark Portal and First War — Warcraft Wiki search",
      ["kind"] = "external_reference",
      ["classification"] = "secondary",
      ["reference"] = "https://warcraft.wiki.gg/index.php?search=Dark+Portal",
      ["url"] = "https://warcraft.wiki.gg/index.php?search=Dark+Portal",
      ["attribution"] = "Warcraft Wiki contributors",
      ["license"] = "CC BY-SA 4.0",
      ["verificationStatus"] = "unverified",
    },
    {
      ["id"] = "src_wowhead_classic_lore",
      ["publisher"] = "Wowhead",
      ["title"] = "Dark Portal — Wowhead search",
      ["kind"] = "external_reference",
      ["classification"] = "secondary",
      ["reference"] = "https://www.wowhead.com/search?q=Dark+Portal",
      ["url"] = "https://www.wowhead.com/search?q=Dark+Portal",
      ["attribution"] = "Wowhead",
      ["license"] = "Proprietary; reference link only, do not copy text",
      ["verificationStatus"] = "unverified",
    },
  },
  ["discoveryGates"] = {
    {
      ["id"] = "sample_gate_black_temple_defeated",
      ["label"] = "[Sample] The player has defeated the sample raid boss",
      ["signalType"] = "encounter",
      ["minimumDetailLevel"] = "deep",
    },
    {
      ["id"] = "fixture_waypoint_discovered",
      ["label"] = "The player has discovered Example Waypoint",
      ["signalType"] = "manual_confirmation",
      ["minimumDetailLevel"] = "story",
    },
    {
      ["id"] = "gate_black_temple_defeated",
      ["label"] = "The player has defeated Illidan in the Black Temple",
      ["signalType"] = "encounter",
      ["minimumDetailLevel"] = "deep",
    },
    {
      ["id"] = "gate_fall_of_lordaeron_witnessed",
      ["label"] = "The player has learned the full account of Lordaeron's fall",
      ["signalType"] = "quest",
      ["minimumDetailLevel"] = "deep",
    },
  },
  ["statements"] = {
    {
      ["id"] = "sample_illidan_stormrage_quick",
      ["entityId"] = "sample_illidan_stormrage",
      ["detailLevel"] = "quick",
      ["text"] = "[Sample placeholder] One-sentence quick summary.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "sample_illidan_stormrage_story",
      ["entityId"] = "sample_illidan_stormrage",
      ["detailLevel"] = "story",
      ["text"] = "[Sample placeholder] A short paragraph of background context, safe to show without spoiling anything.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
        "sample_src_placeholder_secondary",
      },
      ["spoilerLevel"] = "context",
    },
    {
      ["id"] = "sample_illidan_stormrage_deep",
      ["entityId"] = "sample_illidan_stormrage",
      ["detailLevel"] = "deep",
      ["text"] = "[Sample placeholder] Deep-dive text revealing how the storyline concludes. Gated behind both a discovery gate and the ending spoiler level.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["discoveryGateIds"] = {
        "sample_gate_black_temple_defeated",
      },
      ["spoilerLevel"] = "ending",
    },
    {
      ["id"] = "sample_illidan_stormrage_reference",
      ["entityId"] = "sample_illidan_stormrage",
      ["detailLevel"] = "reference",
      ["text"] = "[Sample placeholder] Structured factual reference: Race: Night elf (demon). First appearance: Warcraft III. Notable titles: The Betrayer, Lord of Outland.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "sample_illidan_stormrage_micro",
      ["entityId"] = "sample_illidan_stormrage",
      ["detailLevel"] = "micro",
      ["text"] = "[Sample placeholder] One-sentence micro summary.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "sample_illidan_stormrage_disputed_motive",
      ["entityId"] = "sample_illidan_stormrage",
      ["detailLevel"] = "deep",
      ["text"] = "[Sample placeholder] Demonstrates a documented retcon: an older source's account of motive conflicts with a newer, more authoritative account.",
      ["canonStatus"] = "disputed",
      ["epistemicStatus"] = "interpretation",
      ["sourceIds"] = {
        "sample_src_conflicting_retcon",
        "sample_src_placeholder_secondary",
      },
      ["spoilerLevel"] = "major_reveal",
    },
    {
      ["id"] = "sample_malfurion_stormrage_quick",
      ["entityId"] = "sample_malfurion_stormrage",
      ["detailLevel"] = "quick",
      ["text"] = "[Sample placeholder] One-sentence quick summary.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "sample_black_temple_quick",
      ["entityId"] = "sample_black_temple",
      ["detailLevel"] = "quick",
      ["text"] = "[Sample placeholder] One-sentence quick summary.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "sample_war_of_the_ancients_quick",
      ["entityId"] = "sample_war_of_the_ancients",
      ["detailLevel"] = "quick",
      ["text"] = "[Sample placeholder] One-sentence quick summary.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "example_wayfinder_quick_fact",
      ["entityId"] = "example_wayfinder",
      ["detailLevel"] = "quick",
      ["text"] = "Example Wayfinder is associated with Example Waypoint.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "fixture_author_note",
      },
    },
    {
      ["id"] = "example_wayfinder_story_interpretation",
      ["entityId"] = "example_wayfinder",
      ["detailLevel"] = "story",
      ["text"] = "The wayfinder may treat the waypoint as a symbol of return.",
      ["canonStatus"] = "unknown",
      ["epistemicStatus"] = "interpretation",
      ["sourceIds"] = {
        "fixture_author_note",
      },
      ["discoveryGateIds"] = {
        "fixture_waypoint_discovered",
      },
    },
    {
      ["id"] = "illidan_stormrage_quick",
      ["entityId"] = "illidan_stormrage",
      ["detailLevel"] = "quick",
      ["text"] = "Illidan Stormrage is a night elf turned demon, twin brother of Malfurion, and the first demon hunter.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "illidan_stormrage_story",
      ["entityId"] = "illidan_stormrage",
      ["detailLevel"] = "story",
      ["text"] = "Once imprisoned for ten thousand years for creating a second Well of Eternity, Illidan was freed to fight the Burning Legion. He later fled to Outland, built an army of demon hunters, and ruled from the Black Temple.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "illidan_stormrage_deep",
      ["entityId"] = "illidan_stormrage",
      ["detailLevel"] = "deep",
      ["text"] = "Adventurers, aided by Akama and Illidan's old jailer Maiev Shadowsong, stormed the Black Temple and ended his rule over Outland.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["discoveryGateIds"] = {
        "gate_black_temple_defeated",
      },
    },
    {
      ["id"] = "malfurion_stormrage_quick",
      ["entityId"] = "malfurion_stormrage",
      ["detailLevel"] = "quick",
      ["text"] = "Malfurion Stormrage is Illidan's twin brother and the first druid of the night elves.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "malfurion_stormrage_story",
      ["entityId"] = "malfurion_stormrage",
      ["detailLevel"] = "story",
      ["text"] = "Malfurion opposed his brother's methods throughout the War of the Ancients and its aftermath, eventually banishing Illidan after his transformation into a demon.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "malfurion_stormrage_deep",
      ["entityId"] = "malfurion_stormrage",
      ["detailLevel"] = "deep",
      ["text"] = "Despite their long rivalry, Malfurion's disputes with Illidan were rooted in differing views on how to face the Burning Legion rather than simple animosity.",
      ["canonStatus"] = "unknown",
      ["epistemicStatus"] = "interpretation",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "tyrande_whisperwind_quick",
      ["entityId"] = "tyrande_whisperwind",
      ["detailLevel"] = "quick",
      ["text"] = "Tyrande Whisperwind is the High Priestess of Elune and a childhood friend of both Stormrage brothers.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "tyrande_whisperwind_story",
      ["entityId"] = "tyrande_whisperwind",
      ["detailLevel"] = "story",
      ["text"] = "Tyrande freed Illidan from his ten-thousand-year imprisonment to help fight the Burning Legion during the Third War, a decision that strained her bond with Malfurion.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "maiev_shadowsong_quick",
      ["entityId"] = "maiev_shadowsong",
      ["detailLevel"] = "quick",
      ["text"] = "Maiev Shadowsong is a Warden of the night elves who imprisoned Illidan for millennia.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "maiev_shadowsong_story",
      ["entityId"] = "maiev_shadowsong",
      ["detailLevel"] = "story",
      ["text"] = "After Illidan's release, Maiev pursued him relentlessly across Kalimdor and Outland, determined to see him imprisoned again.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "maiev_shadowsong_deep",
      ["entityId"] = "maiev_shadowsong",
      ["detailLevel"] = "deep",
      ["text"] = "Maiev's role in confronting Illidan at the Black Temple closed out a pursuit that had defined much of her life.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["discoveryGateIds"] = {
        "gate_black_temple_defeated",
      },
    },
    {
      ["id"] = "akama_quick",
      ["entityId"] = "akama",
      ["detailLevel"] = "quick",
      ["text"] = "Akama is a broken draenei leader who once served Illidan in Outland.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "akama_story",
      ["entityId"] = "akama",
      ["detailLevel"] = "story",
      ["text"] = "Akama's people were indebted to Illidan for defending them from the fel orcs, but Akama grew disillusioned with Illidan's rule over the Black Temple.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "kaelthas_sunstrider_quick",
      ["entityId"] = "kaelthas_sunstrider",
      ["detailLevel"] = "quick",
      ["text"] = "Kael'thas Sunstrider is a blood elf prince who allied his people with Illidan in Outland.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "kaelthas_sunstrider_story",
      ["entityId"] = "kaelthas_sunstrider",
      ["detailLevel"] = "story",
      ["text"] = "Seeking a cure for the blood elves' magic addiction, Kael'thas pledged his people's allegiance to Illidan, though the alliance did not last.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "lady_vashj_quick",
      ["entityId"] = "lady_vashj",
      ["detailLevel"] = "quick",
      ["text"] = "Lady Vashj is a naga sorceress and one of Illidan's most loyal lieutenants.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "lady_vashj_story",
      ["entityId"] = "lady_vashj",
      ["detailLevel"] = "story",
      ["text"] = "Vashj commanded Illidan's naga forces in Outland, securing water and resources for his stronghold at the Black Temple.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "guldan_quick",
      ["entityId"] = "guldan",
      ["detailLevel"] = "quick",
      ["text"] = "Gul'dan is an orc warlock whose skull became a source of demonic power long after his death.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "guldan_story",
      ["entityId"] = "guldan",
      ["detailLevel"] = "story",
      ["text"] = "The Skull of Gul'dan, discovered years after the warlock's death, held fel energy that would later transform Illidan into a demon.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "black_temple_quick",
      ["entityId"] = "black_temple",
      ["detailLevel"] = "quick",
      ["text"] = "The Black Temple is a former draenei temple in Shadowmoon Valley that Illidan claimed as his stronghold.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "black_temple_story",
      ["entityId"] = "black_temple",
      ["detailLevel"] = "story",
      ["text"] = "Originally known as the Temple of Karabor, the site became the seat of Illidan's rule over Outland until adventurers and his former allies brought about his defeat there.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
    },
    {
      ["id"] = "black_temple_deep",
      ["entityId"] = "black_temple",
      ["detailLevel"] = "deep",
      ["text"] = "The fall of the Black Temple marked the end of Illidan's control over Outland and the beginning of Akama's efforts to restore the temple.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
      ["discoveryGateIds"] = {
        "gate_black_temple_defeated",
      },
    },
    {
      ["id"] = "outland_quick",
      ["entityId"] = "outland",
      ["detailLevel"] = "quick",
      ["text"] = "Outland is the shattered remains of the orc homeworld Draenor.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "outland_story",
      ["entityId"] = "outland",
      ["detailLevel"] = "story",
      ["text"] = "After the Dark Portal reopened, Outland became the stage for Illidan's exile, his rule from the Black Temple, and the arrival of adventurers from Azeroth.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
    },
    {
      ["id"] = "skull_of_guldan_quick",
      ["entityId"] = "skull_of_guldan",
      ["detailLevel"] = "quick",
      ["text"] = "The Skull of Gul'dan is a demonic artifact tied to the orc warlock's fel magic.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "skull_of_guldan_story",
      ["entityId"] = "skull_of_guldan",
      ["detailLevel"] = "story",
      ["text"] = "When Illidan absorbed the skull's fel energy during the Third War, he transformed into a demon in order to defeat the dreadlord Tichondrius.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "the_illidari_quick",
      ["entityId"] = "the_illidari",
      ["detailLevel"] = "quick",
      ["text"] = "The Illidari are demon hunters trained by Illidan to fight the Burning Legion using its own methods.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "the_illidari_story",
      ["entityId"] = "the_illidari",
      ["detailLevel"] = "story",
      ["text"] = "Formed from Illidan's most devoted followers, the Illidari embraced fel powers similar to their master's in order to combat demons on equal footing.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "war_of_the_ancients_quick",
      ["entityId"] = "war_of_the_ancients",
      ["detailLevel"] = "quick",
      ["text"] = "The War of the Ancients was an ancient war against the Burning Legion fought at the Well of Eternity.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "war_of_the_ancients_story",
      ["entityId"] = "war_of_the_ancients",
      ["detailLevel"] = "story",
      ["text"] = "During the war, Illidan's choices set him at odds with his brother Malfurion, a rift that would echo for ten thousand years.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
    },
    {
      ["id"] = "fall_of_the_black_temple_quick",
      ["entityId"] = "fall_of_the_black_temple",
      ["detailLevel"] = "quick",
      ["text"] = "The Fall of the Black Temple refers to the battle in which Illidan's rule over Outland was ended.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "fall_of_the_black_temple_story",
      ["entityId"] = "fall_of_the_black_temple",
      ["detailLevel"] = "story",
      ["text"] = "Adventurers from the Alliance and Horde, working alongside Akama and Maiev Shadowsong, breached the Black Temple and confronted Illidan directly.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
    },
    {
      ["id"] = "fall_of_the_black_temple_deep",
      ["entityId"] = "fall_of_the_black_temple",
      ["detailLevel"] = "deep",
      ["text"] = "Illidan's defeat at the Black Temple allowed Akama to reclaim the temple and marked a turning point in the fight against the Burning Legion's influence over Outland.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
      ["discoveryGateIds"] = {
        "gate_black_temple_defeated",
      },
    },
    {
      ["id"] = "hellfire_peninsula_quick",
      ["entityId"] = "hellfire_peninsula",
      ["detailLevel"] = "quick",
      ["text"] = "Hellfire Peninsula is the scarred zone surrounding the Dark Portal in Outland.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
    },
    {
      ["id"] = "hellfire_peninsula_story",
      ["entityId"] = "hellfire_peninsula",
      ["detailLevel"] = "story",
      ["text"] = "As the first zone most adventurers reach after passing through the Dark Portal, Hellfire Peninsula introduces the fel-corrupted state of Outland under the influence of the Burning Legion and Illidan's forces.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
    },
    {
      ["id"] = "arthas_menethil_quick",
      ["entityId"] = "arthas_menethil",
      ["detailLevel"] = "quick",
      ["text"] = "Arthas Menethil was the Crown Prince of Lordaeron before his fall to corruption.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "arthas_menethil_story",
      ["entityId"] = "arthas_menethil",
      ["detailLevel"] = "story",
      ["text"] = "Seeking to stop a plague spreading through his kingdom, Arthas took increasingly extreme measures, ultimately claiming the runeblade Frostmourne and turning against his own people.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["spoilerLevel"] = "context",
    },
    {
      ["id"] = "arthas_menethil_deep",
      ["entityId"] = "arthas_menethil",
      ["detailLevel"] = "deep",
      ["text"] = "Arthas's actions culminated in the fall of Lordaeron's capital and his eventual fusion with the Lich King, sealing his transformation into an even greater threat.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["discoveryGateIds"] = {
        "gate_fall_of_lordaeron_witnessed",
      },
      ["spoilerLevel"] = "major_reveal",
    },
    {
      ["id"] = "jaina_proudmoore_quick",
      ["entityId"] = "jaina_proudmoore",
      ["detailLevel"] = "quick",
      ["text"] = "Jaina Proudmoore is a human sorceress who was once one of Arthas's closest companions.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "jaina_proudmoore_story",
      ["entityId"] = "jaina_proudmoore",
      ["detailLevel"] = "story",
      ["text"] = "Jaina tried to warn others of Arthas's growing recklessness during the Third War, and led survivors away from Lordaeron to found a new home on Kalimdor.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["spoilerLevel"] = "context",
    },
    {
      ["id"] = "uther_quick",
      ["entityId"] = "uther",
      ["detailLevel"] = "quick",
      ["text"] = "Uther the Lightbringer was a paladin of the Silver Hand and Arthas's mentor.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "uther_story",
      ["entityId"] = "uther",
      ["detailLevel"] = "story",
      ["text"] = "Uther refused to follow Arthas's increasingly ruthless orders, and was ultimately killed by his own former student.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["spoilerLevel"] = "reveal",
    },
    {
      ["id"] = "kelthuzad_quick",
      ["entityId"] = "kelthuzad",
      ["detailLevel"] = "quick",
      ["text"] = "Kel'Thuzad is a human archmage who founded the Cult of the Damned in service to the Lich King.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "kelthuzad_story",
      ["entityId"] = "kelthuzad",
      ["detailLevel"] = "story",
      ["text"] = "Kel'Thuzad abandoned the Kirin Tor to spread the plague of undeath, helping pave the way for the Scourge's invasion of Lordaeron.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["spoilerLevel"] = "context",
    },
    {
      ["id"] = "sylvanas_windrunner_quick",
      ["entityId"] = "sylvanas_windrunner",
      ["detailLevel"] = "quick",
      ["text"] = "Sylvanas Windrunner is the former Ranger-General of Silvermoon who now leads the Forsaken.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "sylvanas_windrunner_story",
      ["entityId"] = "sylvanas_windrunner",
      ["detailLevel"] = "story",
      ["text"] = "Slain defending her homeland and raised as a banshee by the Scourge, Sylvanas eventually broke free of the Lich King's control and rallied other free undead into the Forsaken.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["spoilerLevel"] = "reveal",
    },
    {
      ["id"] = "the_scourge_quick",
      ["entityId"] = "the_scourge",
      ["detailLevel"] = "quick",
      ["text"] = "The Scourge is the undead army raised by the Lich King to conquer Lordaeron.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "the_scourge_story",
      ["entityId"] = "the_scourge",
      ["detailLevel"] = "story",
      ["text"] = "Spread through a magical plague, the Scourge swept across Lordaeron during the Third War, turning the living into undead servants of the Lich King.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["spoilerLevel"] = "context",
    },
    {
      ["id"] = "the_forsaken_quick",
      ["entityId"] = "the_forsaken",
      ["detailLevel"] = "quick",
      ["text"] = "The Forsaken are undead who broke free of the Lich King's control under Sylvanas Windrunner.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "the_forsaken_story",
      ["entityId"] = "the_forsaken",
      ["detailLevel"] = "story",
      ["text"] = "United by their reclaimed free will, the Forsaken carved out a home in the ruins of Lordaeron and later allied themselves with the Horde.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["spoilerLevel"] = "context",
    },
    {
      ["id"] = "lordaeron_quick",
      ["entityId"] = "lordaeron",
      ["detailLevel"] = "quick",
      ["text"] = "Lordaeron was the human kingdom whose capital fell during the Scourge invasion.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "lordaeron_story",
      ["entityId"] = "lordaeron",
      ["detailLevel"] = "story",
      ["text"] = "Once the seat of the Alliance of Lordaeron, the kingdom's capital ultimately fell to the Scourge and later became the ruined home of the Forsaken.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["spoilerLevel"] = "reveal",
    },
    {
      ["id"] = "third_war_quick",
      ["entityId"] = "third_war",
      ["detailLevel"] = "quick",
      ["text"] = "The Third War was the Scourge invasion of Lordaeron and the wider conflict that followed.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["spoilerLevel"] = "safe",
    },
    {
      ["id"] = "third_war_story",
      ["entityId"] = "third_war",
      ["detailLevel"] = "story",
      ["text"] = "The Third War reshaped Azeroth's factions: the Scourge devastated Lordaeron, the orcs founded a new Horde on Kalimdor, and Illidan and the night elves clashed with the Burning Legion.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["spoilerLevel"] = "context",
    },
    {
      ["id"] = "fall_of_lordaeron_quick",
      ["entityId"] = "fall_of_lordaeron",
      ["detailLevel"] = "quick",
      ["text"] = "The Fall of Lordaeron was the destruction of the kingdom's capital at Arthas's hand.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["spoilerLevel"] = "reveal",
    },
    {
      ["id"] = "fall_of_lordaeron_story",
      ["entityId"] = "fall_of_lordaeron",
      ["detailLevel"] = "story",
      ["text"] = "Arthas's return to Lordaeron, corrupted and wielding Frostmourne, marked the definitive end of the kingdom his family once ruled.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["spoilerLevel"] = "major_reveal",
    },
    {
      ["id"] = "dark_portal_quick",
      ["entityId"] = "dark_portal",
      ["detailLevel"] = "quick",
      ["text"] = "The Dark Portal is a massive stone ring linking Azeroth to Outland.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "dark_portal_story",
      ["entityId"] = "dark_portal",
      ["detailLevel"] = "story",
      ["text"] = "First opened by Medivh to allow the orcs onto Azeroth, the portal was later destroyed and lay dormant for years before Cho'gall reopened it just before the Burning Crusade.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
    },
    {
      ["id"] = "dark_portal_deep",
      ["entityId"] = "dark_portal",
      ["detailLevel"] = "deep",
      ["text"] = "The Alliance built Nethergarde Keep nearby to keep watch over the ruined portal, never expecting it would one day reopen on its own.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
    },
    {
      ["id"] = "medivh_quick",
      ["entityId"] = "medivh",
      ["detailLevel"] = "quick",
      ["text"] = "Medivh was the last Guardian of Tirisfal before opening the original Dark Portal.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "medivh_story",
      ["entityId"] = "medivh",
      ["detailLevel"] = "story",
      ["text"] = "Secretly corrupted by the Burning Legion, Medivh opened the Dark Portal to Draenor, allowing the orc clans to invade Azeroth in the First War.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
    },
    {
      ["id"] = "medivh_deep",
      ["entityId"] = "medivh",
      ["detailLevel"] = "deep",
      ["text"] = "How much of Medivh's own will remained during his corruption is still debated; some accounts treat him as culpable, others as a tragic vessel for Sargeras's influence.",
      ["canonStatus"] = "disputed",
      ["epistemicStatus"] = "interpretation",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "khadgar_quick",
      ["entityId"] = "khadgar",
      ["detailLevel"] = "quick",
      ["text"] = "Khadgar was Medivh's apprentice and later a leading Alliance mage.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "khadgar_story",
      ["entityId"] = "khadgar",
      ["detailLevel"] = "story",
      ["text"] = "Khadgar helped uncover Medivh's corruption during the First War and, years later, became a key figure guiding adventurers through the reopened Dark Portal.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
    },
    {
      ["id"] = "draenor_quick",
      ["entityId"] = "draenor",
      ["detailLevel"] = "quick",
      ["text"] = "Draenor was the orc homeworld beyond the Dark Portal.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "draenor_story",
      ["entityId"] = "draenor",
      ["detailLevel"] = "story",
      ["text"] = "Draenor was later shattered into the fragmented realm now known as Outland.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
    },
    {
      ["id"] = "the_horde_quick",
      ["entityId"] = "the_horde",
      ["detailLevel"] = "quick",
      ["text"] = "The Horde began as the orc clans who invaded Azeroth through the Dark Portal.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "the_horde_story",
      ["entityId"] = "the_horde",
      ["detailLevel"] = "story",
      ["text"] = "After years of internment following the First and Second Wars, Thrall freed the orcs and reformed the Horde on Kalimdor.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
    },
    {
      ["id"] = "the_alliance_quick",
      ["entityId"] = "the_alliance",
      ["detailLevel"] = "quick",
      ["text"] = "The Alliance is a coalition formed to oppose the orcish invasions of Azeroth.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "the_alliance_story",
      ["entityId"] = "the_alliance",
      ["detailLevel"] = "story",
      ["text"] = "Formed from humans, dwarves, night elves, gnomes, and other races, the Alliance has remained an uneasy rival of the Horde since the First War.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
    },
    {
      ["id"] = "thrall_quick",
      ["entityId"] = "thrall",
      ["detailLevel"] = "quick",
      ["text"] = "Thrall is the Warchief who reformed the Horde after freeing the orcs from internment.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "thrall_story",
      ["entityId"] = "thrall",
      ["detailLevel"] = "story",
      ["text"] = "Raised in captivity, Thrall escaped and rallied the orc clans to found a new Horde built on honor rather than demonic corruption.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
    },
    {
      ["id"] = "cho_gall_quick",
      ["entityId"] = "cho_gall",
      ["detailLevel"] = "quick",
      ["text"] = "Cho'gall is a Twilight's Hammer cult leader who reopened the Dark Portal.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "cho_gall_story",
      ["entityId"] = "cho_gall",
      ["detailLevel"] = "story",
      ["text"] = "Shortly before the Burning Crusade, Cho'gall used a powerful relic to reopen the long-dormant Dark Portal, drawing adventurers' attention to Outland once more.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_wowhead_classic_lore",
      },
    },
    {
      ["id"] = "first_war_quick",
      ["entityId"] = "first_war",
      ["detailLevel"] = "quick",
      ["text"] = "The First War was the initial orcish invasion of Azeroth through the Dark Portal.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "first_war_story",
      ["entityId"] = "first_war",
      ["detailLevel"] = "story",
      ["text"] = "The orc clans, empowered by fel magic, overwhelmed the kingdom of Azeroth, beginning generations of conflict between orcs and humans.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
    },
    {
      ["id"] = "first_war_deep",
      ["entityId"] = "first_war",
      ["detailLevel"] = "deep",
      ["text"] = "Both Medivh and a young Khadgar played pivotal, if very different, roles in how the First War began and was ultimately exposed.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
    },
    {
      ["id"] = "blasted_lands_quick",
      ["entityId"] = "blasted_lands",
      ["detailLevel"] = "quick",
      ["text"] = "The Blasted Lands are a scarred region of Azeroth surrounding the Dark Portal.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "blasted_lands_story",
      ["entityId"] = "blasted_lands",
      ["detailLevel"] = "story",
      ["text"] = "The land here was twisted by the portal's destruction, and the Alliance built Nethergarde Keep nearby to keep watch over the ruins.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_wowhead_classic_lore",
      },
    },
    {
      ["id"] = "nethergarde_keep_quick",
      ["entityId"] = "nethergarde_keep",
      ["detailLevel"] = "quick",
      ["text"] = "Nethergarde Keep is an Alliance fortress watching over the Dark Portal.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "nethergarde_keep_story",
      ["entityId"] = "nethergarde_keep",
      ["detailLevel"] = "story",
      ["text"] = "Built in the Blasted Lands, the keep gave the Alliance a forward base to monitor the ruined portal for any sign of renewed activity.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_wowhead_classic_lore",
      },
    },
    {
      ["id"] = "opening_of_the_dark_portal_quick",
      ["entityId"] = "opening_of_the_dark_portal",
      ["detailLevel"] = "quick",
      ["text"] = "The Opening of the Dark Portal was the world event that reactivated the portal just before the Burning Crusade.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
    },
    {
      ["id"] = "opening_of_the_dark_portal_story",
      ["entityId"] = "opening_of_the_dark_portal",
      ["detailLevel"] = "story",
      ["text"] = "Cho'gall's ritual reopened the portal, drawing invasion forces onto Azeroth and giving adventurers their first path into Outland.",
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_wowhead_classic_lore",
      },
    },
  },
  ["relationships"] = {
    {
      ["id"] = "sample_illidan_sibling_of_malfurion",
      ["subjectId"] = "sample_illidan_stormrage",
      ["predicate"] = "sibling_of",
      ["objectId"] = "sample_malfurion_stormrage",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Placeholder: demonstrates the new sibling_of predicate.",
    },
    {
      ["id"] = "sample_illidan_rules_black_temple",
      ["subjectId"] = "sample_illidan_stormrage",
      ["predicate"] = "rules",
      ["objectId"] = "sample_black_temple",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Placeholder: demonstrates the new rules predicate.",
    },
    {
      ["id"] = "sample_illidari_led_by_illidan",
      ["subjectId"] = "sample_the_illidari",
      ["predicate"] = "led_by",
      ["objectId"] = "sample_illidan_stormrage",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Placeholder: demonstrates the new led_by predicate.",
    },
    {
      ["id"] = "sample_illidari_part_of_black_temple",
      ["subjectId"] = "sample_the_illidari",
      ["predicate"] = "part_of",
      ["objectId"] = "sample_black_temple",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Placeholder: demonstrates the new part_of predicate.",
    },
    {
      ["id"] = "sample_illidan_opposes_malfurion",
      ["subjectId"] = "sample_illidan_stormrage",
      ["predicate"] = "opposes",
      ["objectId"] = "sample_malfurion_stormrage",
      ["sourceIds"] = {
        "sample_src_placeholder_secondary",
      },
      ["canonStatus"] = "disputed",
      ["epistemicStatus"] = "interpretation",
      ["context"] = "Placeholder: demonstrates the new opposes predicate.",
    },
    {
      ["id"] = "sample_illidan_participated_in_war_of_the_ancients",
      ["subjectId"] = "sample_illidan_stormrage",
      ["predicate"] = "participated_in",
      ["objectId"] = "sample_war_of_the_ancients",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "sample_illidan_participated_in_fall_of_the_black_temple",
      ["subjectId"] = "sample_illidan_stormrage",
      ["predicate"] = "participated_in",
      ["objectId"] = "sample_fall_of_the_black_temple",
      ["sourceIds"] = {
        "sample_src_placeholder_primary",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "sample_malfurion_supports_the_illidari",
      ["subjectId"] = "sample_malfurion_stormrage",
      ["predicate"] = "supports",
      ["objectId"] = "sample_the_illidari",
      ["sourceIds"] = {
        "sample_src_placeholder_secondary",
      },
      ["canonStatus"] = "unknown",
      ["epistemicStatus"] = "speculation",
      ["context"] = "Placeholder: demonstrates the new supports predicate and a speculation-classified fact.",
    },
    {
      ["id"] = "example_wayfinder_located_at_waypoint",
      ["subjectId"] = "example_wayfinder",
      ["predicate"] = "located_at",
      ["objectId"] = "example_waypoint",
      ["sourceIds"] = {
        "fixture_author_note",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "illidan_stormrage_related_to_malfurion_stormrage",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "related_to",
      ["objectId"] = "malfurion_stormrage",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Twin brothers.",
    },
    {
      ["id"] = "illidan_stormrage_enemy_of_maiev_shadowsong",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "enemy_of",
      ["objectId"] = "maiev_shadowsong",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "illidan_stormrage_allied_with_lady_vashj",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "allied_with",
      ["objectId"] = "lady_vashj",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "illidan_stormrage_allied_with_kaelthas_sunstrider",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "allied_with",
      ["objectId"] = "kaelthas_sunstrider",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Kael'thas later defected from Illidan's service.",
    },
    {
      ["id"] = "illidan_stormrage_allied_with_akama",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "allied_with",
      ["objectId"] = "akama",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Akama later worked against Illidan's rule.",
    },
    {
      ["id"] = "illidan_stormrage_created_the_illidari",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "created",
      ["objectId"] = "the_illidari",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "illidan_stormrage_located_at_black_temple",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "located_at",
      ["objectId"] = "black_temple",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "illidan_stormrage_located_at_outland",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "located_at",
      ["objectId"] = "outland",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "illidan_stormrage_participated_in_war_of_the_ancients",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "participated_in",
      ["objectId"] = "war_of_the_ancients",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "illidan_stormrage_participated_in_fall_of_the_black_temple",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "participated_in",
      ["objectId"] = "fall_of_the_black_temple",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "guldan_created_skull_of_guldan",
      ["subjectId"] = "guldan",
      ["predicate"] = "created",
      ["objectId"] = "skull_of_guldan",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "illidan_stormrage_associated_with_skull_of_guldan",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "associated_with",
      ["objectId"] = "skull_of_guldan",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "outland_contains_black_temple",
      ["subjectId"] = "outland",
      ["predicate"] = "contains",
      ["objectId"] = "black_temple",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "outland_contains_hellfire_peninsula",
      ["subjectId"] = "outland",
      ["predicate"] = "contains",
      ["objectId"] = "hellfire_peninsula",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "maiev_shadowsong_participated_in_fall_of_the_black_temple",
      ["subjectId"] = "maiev_shadowsong",
      ["predicate"] = "participated_in",
      ["objectId"] = "fall_of_the_black_temple",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "akama_participated_in_fall_of_the_black_temple",
      ["subjectId"] = "akama",
      ["predicate"] = "participated_in",
      ["objectId"] = "fall_of_the_black_temple",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_wowhead_black_temple",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "tyrande_whisperwind_allied_with_malfurion_stormrage",
      ["subjectId"] = "tyrande_whisperwind",
      ["predicate"] = "allied_with",
      ["objectId"] = "malfurion_stormrage",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "malfurion_stormrage_participated_in_war_of_the_ancients",
      ["subjectId"] = "malfurion_stormrage",
      ["predicate"] = "participated_in",
      ["objectId"] = "war_of_the_ancients",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "tyrande_whisperwind_participated_in_war_of_the_ancients",
      ["subjectId"] = "tyrande_whisperwind",
      ["predicate"] = "participated_in",
      ["objectId"] = "war_of_the_ancients",
      ["sourceIds"] = {
        "src_lorebuddy_contributors",
        "src_warcraft_wiki_illidan",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "arthas_allied_with_jaina",
      ["subjectId"] = "arthas_menethil",
      ["predicate"] = "allied_with",
      ["objectId"] = "jaina_proudmoore",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Companions before the Third War's devastation.",
    },
    {
      ["id"] = "arthas_associated_with_uther",
      ["subjectId"] = "arthas_menethil",
      ["predicate"] = "associated_with",
      ["objectId"] = "uther",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Uther's student, later his killer.",
    },
    {
      ["id"] = "arthas_enemy_of_uther",
      ["subjectId"] = "arthas_menethil",
      ["predicate"] = "enemy_of",
      ["objectId"] = "uther",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "arthas_rules_the_scourge",
      ["subjectId"] = "arthas_menethil",
      ["predicate"] = "rules",
      ["objectId"] = "the_scourge",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "kelthuzad_member_of_the_scourge",
      ["subjectId"] = "kelthuzad",
      ["predicate"] = "member_of",
      ["objectId"] = "the_scourge",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "the_scourge_participated_in_third_war",
      ["subjectId"] = "the_scourge",
      ["predicate"] = "participated_in",
      ["objectId"] = "third_war",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "the_scourge_participated_in_fall_of_lordaeron",
      ["subjectId"] = "the_scourge",
      ["predicate"] = "participated_in",
      ["objectId"] = "fall_of_lordaeron",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "arthas_participated_in_fall_of_lordaeron",
      ["subjectId"] = "arthas_menethil",
      ["predicate"] = "participated_in",
      ["objectId"] = "fall_of_lordaeron",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "fall_of_lordaeron_located_at_lordaeron",
      ["subjectId"] = "fall_of_lordaeron",
      ["predicate"] = "located_at",
      ["objectId"] = "lordaeron",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "sylvanas_enemy_of_arthas",
      ["subjectId"] = "sylvanas_windrunner",
      ["predicate"] = "enemy_of",
      ["objectId"] = "arthas_menethil",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Slain by Arthas's forces, later raised and enslaved by the Scourge before breaking free.",
    },
    {
      ["id"] = "sylvanas_led_by_own_the_forsaken",
      ["subjectId"] = "the_forsaken",
      ["predicate"] = "led_by",
      ["objectId"] = "sylvanas_windrunner",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "the_forsaken_part_of_lordaeron",
      ["subjectId"] = "the_forsaken",
      ["predicate"] = "part_of",
      ["objectId"] = "lordaeron",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "The Forsaken claimed the ruins of Lordaeron's capital as their home.",
    },
    {
      ["id"] = "the_forsaken_supports_the_horde",
      ["subjectId"] = "the_forsaken",
      ["predicate"] = "supports",
      ["objectId"] = "the_horde",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Cross-file link: the_horde is defined in tier1-azeroth-prerequisite-dataset.json.",
    },
    {
      ["id"] = "jaina_participated_in_third_war",
      ["subjectId"] = "jaina_proudmoore",
      ["predicate"] = "participated_in",
      ["objectId"] = "third_war",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "uther_participated_in_third_war",
      ["subjectId"] = "uther",
      ["predicate"] = "participated_in",
      ["objectId"] = "third_war",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "illidan_participated_in_third_war",
      ["subjectId"] = "illidan_stormrage",
      ["predicate"] = "participated_in",
      ["objectId"] = "third_war",
      ["sourceIds"] = {
        "src_lorebuddy_third_war_contributors",
        "src_warcraft_wiki_third_war",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Cross-file link: illidan_stormrage is defined in illidan-vertical-slice-dataset.json.",
    },
    {
      ["id"] = "medivh_created_dark_portal",
      ["subjectId"] = "medivh",
      ["predicate"] = "created",
      ["objectId"] = "dark_portal",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "khadgar_associated_with_medivh",
      ["subjectId"] = "khadgar",
      ["predicate"] = "associated_with",
      ["objectId"] = "medivh",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Medivh's apprentice.",
    },
    {
      ["id"] = "khadgar_participated_in_first_war",
      ["subjectId"] = "khadgar",
      ["predicate"] = "participated_in",
      ["objectId"] = "first_war",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "medivh_participated_in_first_war",
      ["subjectId"] = "medivh",
      ["predicate"] = "participated_in",
      ["objectId"] = "first_war",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "the_horde_participated_in_first_war",
      ["subjectId"] = "the_horde",
      ["predicate"] = "participated_in",
      ["objectId"] = "first_war",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "the_alliance_participated_in_first_war",
      ["subjectId"] = "the_alliance",
      ["predicate"] = "participated_in",
      ["objectId"] = "first_war",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "the_horde_associated_with_draenor",
      ["subjectId"] = "the_horde",
      ["predicate"] = "associated_with",
      ["objectId"] = "draenor",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Orcish homeworld before the invasion of Azeroth.",
    },
    {
      ["id"] = "thrall_member_of_the_horde",
      ["subjectId"] = "thrall",
      ["predicate"] = "member_of",
      ["objectId"] = "the_horde",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Warchief.",
    },
    {
      ["id"] = "dark_portal_located_at_blasted_lands",
      ["subjectId"] = "dark_portal",
      ["predicate"] = "located_at",
      ["objectId"] = "blasted_lands",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_wowhead_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "blasted_lands_contains_nethergarde_keep",
      ["subjectId"] = "blasted_lands",
      ["predicate"] = "contains",
      ["objectId"] = "nethergarde_keep",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_wowhead_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "cho_gall_associated_with_dark_portal",
      ["subjectId"] = "cho_gall",
      ["predicate"] = "associated_with",
      ["objectId"] = "dark_portal",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_wowhead_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Reopened the Dark Portal using a powerful relic.",
    },
    {
      ["id"] = "cho_gall_participated_in_opening_of_the_dark_portal",
      ["subjectId"] = "cho_gall",
      ["predicate"] = "participated_in",
      ["objectId"] = "opening_of_the_dark_portal",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_wowhead_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "opening_of_the_dark_portal_associated_with_dark_portal",
      ["subjectId"] = "opening_of_the_dark_portal",
      ["predicate"] = "associated_with",
      ["objectId"] = "dark_portal",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_wowhead_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
    },
    {
      ["id"] = "the_alliance_related_to_the_horde",
      ["subjectId"] = "the_alliance",
      ["predicate"] = "related_to",
      ["objectId"] = "the_horde",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Uneasy rivals since the First War.",
    },
    {
      ["id"] = "draenor_parent_of_outland",
      ["subjectId"] = "draenor",
      ["predicate"] = "parent_of",
      ["objectId"] = "outland",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_warcraft_wiki_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "Draenor was shattered into the fragmented realm now known as Outland.",
    },
    {
      ["id"] = "dark_portal_associated_with_outland",
      ["subjectId"] = "dark_portal",
      ["predicate"] = "associated_with",
      ["objectId"] = "outland",
      ["sourceIds"] = {
        "src_lorebuddy_tier1_contributors",
        "src_wowhead_classic_lore",
      },
      ["canonStatus"] = "confirmed",
      ["epistemicStatus"] = "fact",
      ["context"] = "The reopened portal is adventurers' route into Outland.",
    },
  },
}
