#!/bin/sh

set -eu

case "${1:-}" in
    validate)
        shift
        exec "$(dirname "$0")/validate_lore_data.py" "$@"
        ;;
    author)
        shift
        exec python3 "$(dirname "$0")/lorebuddy_author.py" "$@"
        ;;
    *)
        printf '%s\n' "Usage: tools/lorebuddy validate|author [dataset]" >&2
        exit 2
        ;;
esac
